#given by github pages anyway
safe: true
lsi: false

# Site settings
title: "Drup's thingies"
baseurl: ""
url: https://drup.github.io

avatar: /assets/img/ogp.png
favicon: /assets/img/ogp.png
language: en

#
# Icons
#
icons:
  rss: true
  github: drup
  email: drupyog<at_thingy>zoho<dot_thingy>com

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
# disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
